
SET SQL DIALECT 3;

/******************************************************************************/
/***                  Estrutura basica UserControl                          ***/
/******************************************************************************/

CREATE TABLE UCLOG (
    APPLICATIONID  VARCHAR(250),
    IDUSER         INTEGER,
    MSG            VARCHAR(250),
    DATA           VARCHAR(14),
    NIVEL          INTEGER
);


CREATE TABLE UCTABMESSAGES (
    IDMSG      INTEGER,
    USRFROM    INTEGER,
    USRTO      INTEGER,
    SUBJECT    VARCHAR(50),
    MSG        VARCHAR(255),
    DTSEND     VARCHAR(12),
    DTRECEIVE  VARCHAR(12)
);


CREATE TABLE UCTABRIGHTS (
    UCIDUSER    INTEGER,
    UCMODULE    VARCHAR(50),
    UCCOMPNAME  VARCHAR(50),
    UCKEY       VARCHAR(250)
);


CREATE TABLE UCTABRIGHTSEX (
    UCIDUSER    INTEGER,
    UCMODULE    VARCHAR(50),
    UCCOMPNAME  VARCHAR(50),
    UCFORMNAME  VARCHAR(50),
    UCKEY       VARCHAR(250)
);


CREATE TABLE UCTABUSERS (
    UCIDUSER       INTEGER,
    UCUSERNAME     VARCHAR(30),
    UCLOGIN        VARCHAR(30),
    UCPASSWORD     VARCHAR(250),
    UCPASSEXPIRED  CHAR(10),
    UCUSEREXPIRED  INTEGER,
    UCUSERDAYSSUN  INTEGER,
    UCEMAIL        VARCHAR(150),
    UCPRIVILEGED   INTEGER,
    UCTYPEREC      CHAR(1),
    UCPROFILE      INTEGER,
    UCKEY          VARCHAR(250),
    UCINATIVE      INTEGER
);


CREATE TABLE UCTABUSERSLOGGED (
    UCIDLOGON        CHAR(38),
    UCIDUSER         INTEGER,
    UCAPPLICATIONID  VARCHAR(50),
    UCMACHINENAME    VARCHAR(50),
    UCDATA           VARCHAR(14)
);


INSERT INTO UCTABUSERS (UCIDUSER, UCUSERNAME, UCLOGIN, UCPASSWORD, UCPASSEXPIRED, UCUSEREXPIRED, UCUSERDAYSSUN, UCEMAIL, UCPRIVILEGED, UCTYPEREC, UCPROFILE, UCKEY, UCINATIVE) VALUES (1, 'Admin', 'Admin', 'jU/GVqfSaD', '05/06/2017', 0, 30, 'teste@teste.com.br', -1, 'U', 2, 'xo56NZisv5nLzxU+dA', 0);
INSERT INTO UCTABUSERS (UCIDUSER, UCUSERNAME, UCLOGIN, UCPASSWORD, UCPASSEXPIRED, UCUSEREXPIRED, UCUSERDAYSSUN, UCEMAIL, UCPRIVILEGED, UCTYPEREC, UCPROFILE, UCKEY, UCINATIVE) VALUES (2, 'Administrador', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'P', NULL, NULL, NULL);

COMMIT WORK;
